### ISSUE TITLE
Model loading

### ISSUE THREAD

**Issue by omnisci3nce** [michaeljclark/glcube#2]
Will you add any examples of model loading in this app skeleton?

**Comment by larkmjc** [comment]
unlikely. if I did it would go in a different repo. there are also the [glkitty](https://github.com/michaeljclark/glkitty), [glyb](https://github.com/michaeljclark/glyb) and [vkgears](https://github.com/michaeljclark/vkgears) demos that use `gl2_util.h`. app skeleton is perhaps a stretch. it might be more correct to say shader loading, plus vertex and index buffer abstraction. it's meant as a minimal additional dependency to be able to write OpenGL ES 2.x compatible api tests and experiments that I can copy-paste, because of course since OpenGL 1.x a bunch of stuff has been moved into the apps like what's in `linmath.h`. this is probably why I use the word skeleton instead of a framework as it is intended as a copy-paste.

I'm closing this issue because there is no associated pull request.
